### ISSUE TITLE
How to start the visualization

### ISSUE THREAD

**Issue by nbanal** [matzehecht/speedtest-monitor#1]
Thanks for the creation of this tool.

Beginner question, how can I start the visualization?

**Comment by matzehecht** [comment]
Have you read the [installation guide](https://github.com/matzehecht/speedtest-monitor#installation)?

**Comment by nbanal** [comment]
Yes.

`docker-compose -p speedtest-monitor up -d` returns:

```
speedtest-monitor_influxdb_1 is up-to-date
speedtest-monitor_speedtest_1 is up-to-date
speedtest-monitor_grafana_1 is up-to-date
```

**Comment by matzehecht** [comment]
You should then be able to access the grafana instance via your browser. Just access the IP address of the machine (or localhost). grafana is running on port 80.

**Comment by nbanal** [comment]
Ok, thanks a lot.

**Comment by nbanal** [comment]
If I understand your Dockerfile correctly, the python script should automatically start to collect data. However on the dashboard, no data is available. Do I manually need to run some scripts?

**Comment by matzehecht** [comment]
I pushed an update. Influxdb had a major release with some changes to the authentication... I missed that...

**Comment by nbanal** [comment]
I confirm that it solved the issue. Thanks a lot
